sudo: false
language: node_js
node_js:
  - 'stable'
  - '8'
script:
  - 'npm run build'
  - 'npm test'
before_deploy:
  - ls -lh data.ndjson full.ndjson
  - npm i semver
  - npm version --no-git-tag-version --force $(./node_modules/.bin/semver -i minor $(npm info db-stations version))
deploy:
  provider: npm
  on:
    branch: master
    node: '6'
  email: 'mail@jannisr.de'
  api_key: ${NPM_KEY}
  skip_cleanup: true
